/**
 * Place verification - resolves free-text place names (from Navia or a chat seed)
 * against Google Places so nothing model-generated is presented to the user as fact.
 *
 * Why this exists: spots typed by a user already went through Places autocomplete and
 * carried a placeId. Spots generated by Navia were dispatched as bare name+description
 * strings, so a permanently-closed or entirely non-existent place looked identical to a
 * verified one. This module closes that gap for every generation path.
 *
 * Caching note (Google Maps Platform terms): place_id may be stored indefinitely and is
 * persisted on the spot. Volatile content - business_status, opening_hours - must not be
 * cached long term, so it lives in a per-session Map only and is re-resolved from the
 * stored place_id when a plan is viewed. That is also the correct behaviour: a cached
 * "open" is exactly the stale fact that makes these itineraries wrong.
 */

export type SpotProvenance =
  /** Resolved to a real, currently operational place. */
  | 'verified'
  /** No Places listing found - shown, but never asserted as fact. */
  | 'unchecked';

export interface PlaceOpeningHours {
  /** e.g. "Monday: 9:00 AM - 5:00 PM" - display only. */
  weekdayText?: string[];
  /** Raw periods, used by the feasibility checks to detect closed-for-your-whole-stay. */
  periods?: Array<{ open?: { day: number; time: string }; close?: { day: number; time: string } }>;
}

export interface PlaceDetails {
  placeId: string;
  name?: string;
  description?: string;
  photoUrl?: string;
  mapUrl?: string;
  lat?: number;
  lng?: number;
  types?: string[];
  businessStatus?: string;
  openingHours?: PlaceOpeningHours;
}

export interface ResolvedSpot {
  name: string;
  description?: string;
  placeId?: string;
  photoUrl?: string;
  mapUrl?: string;
  lat?: number;
  lng?: number;
  types?: string[];
  provenance: SpotProvenance;
  /** ISO timestamp of the check that produced `provenance`. */
  verifiedAt?: string;
}

export interface SpotCandidate {
  name: string;
  description?: string;
}

/** Places returns this for a business that has shut down for good. */
const CLOSED_PERMANENTLY = 'CLOSED_PERMANENTLY';

/**
 * Volatile details, session-scoped only. Never written to Redux or the server.
 * Keyed by placeId so the feasibility engine can read hours without re-fetching
 * within a single planning session.
 */
const volatileDetails = new Map<string, PlaceDetails>();

/** placeId -> details promise, so concurrent resolves of the same place share one call. */
const inFlight = new Map<string, Promise<PlaceDetails | null>>();

/** Resolution attempts keyed by `name|context`, so a re-generate does not re-bill. */
const searchCache = new Map<string, string | null>();

const FIELD_MASK = [
  'place_id',
  'name',
  'geometry',
  'photos',
  'url',
  'editorial_summary',
  'formatted_address',
  'types',
  'business_status',
  'opening_hours',
];

function placesService(): any | null {
  const g = (window as any).google;
  if (!g?.maps?.places) return null;
  return new g.maps.places.PlacesService(document.createElement('div'));
}

/** True once the Maps SDK has loaded; callers degrade to `unchecked` when false. */
export function placesAvailable(): boolean {
  return Boolean((window as any).google?.maps?.places);
}

/** Cached volatile details for a place already resolved this session, if any. */
export function peekPlaceDetails(placeId: string): PlaceDetails | undefined {
  return volatileDetails.get(placeId);
}

/**
 * Guards against Places confidently returning something unrelated - searching
 * "Riverside cafe" in Bangkok should not silently become "Riverside Plaza Hotel".
 * Requires the result to share a meaningful token with what we asked for.
 */
function looksLikeSamePlace(query: string, resultName: string): boolean {
  const norm = (s: string) =>
    s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(t => t.length > 2);
  const q = norm(query);
  const r = new Set(norm(resultName));
  if (q.length === 0 || r.size === 0) return true; // nothing to compare, don't block
  return q.some(token => r.has(token));
}

function readDetails(pl: any): PlaceDetails {
  let photoUrl: string | undefined;
  if (pl.photos?.length) {
    try { photoUrl = pl.photos[0].getUrl({ maxWidth: 480, maxHeight: 320 }); } catch { /* photo url can throw when quota-limited */ }
  }

  let description: string | undefined;
  if (pl.editorial_summary?.overview) {
    description = pl.editorial_summary.overview.split(/\n|\.|!/)[0].trim();
  }
  if (!description && pl.formatted_address) {
    const addr = pl.formatted_address as string;
    const nameLower = (pl.name || '').toLowerCase();
    description = addr.toLowerCase().startsWith(nameLower)
      ? addr.slice((pl.name || '').length).replace(/^,\s*/, '')
      : addr;
  }
  if (!description && Array.isArray(pl.types) && pl.types.length) {
    description = pl.types[0].replace(/_/g, ' ');
  }

  return {
    placeId: pl.place_id,
    name: pl.name,
    description,
    photoUrl,
    mapUrl: pl.url,
    lat: pl.geometry?.location?.lat?.(),
    lng: pl.geometry?.location?.lng?.(),
    types: Array.isArray(pl.types) ? pl.types : undefined,
    businessStatus: pl.business_status,
    openingHours: pl.opening_hours
      ? { weekdayText: pl.opening_hours.weekday_text, periods: pl.opening_hours.periods }
      : undefined,
  };
}

/** Full details for a known placeId. Shared by the resolver and the discover sheet. */
export function getPlaceDetails(placeId: string): Promise<PlaceDetails | null> {
  const cached = volatileDetails.get(placeId);
  if (cached) return Promise.resolve(cached);

  const pending = inFlight.get(placeId);
  if (pending) return pending;

  const svc = placesService();
  if (!svc) return Promise.resolve(null);

  const req = new Promise<PlaceDetails | null>(resolve => {
    svc.getDetails({ placeId, fields: FIELD_MASK }, (pl: any, status: string) => {
      if (status !== 'OK' || !pl) { resolve(null); return; }
      const details = readDetails(pl);
      volatileDetails.set(placeId, details);
      resolve(details);
    });
  }).finally(() => { inFlight.delete(placeId); });

  inFlight.set(placeId, req);
  return req;
}

/** Finds the best placeId for a free-text name within a destination, or null. */
function findPlaceId(name: string, context: string): Promise<string | null> {
  const key = `${name.toLowerCase()}|${context.toLowerCase()}`;
  if (searchCache.has(key)) return Promise.resolve(searchCache.get(key) ?? null);

  const svc = placesService();
  if (!svc) return Promise.resolve(null);

  return new Promise<string | null>(resolve => {
    const query = context ? `${name}, ${context}` : name;
    svc.textSearch({ query }, (results: any[] | null, status: string) => {
      if (status !== 'OK' || !Array.isArray(results) || results.length === 0) {
        searchCache.set(key, null);
        resolve(null);
        return;
      }
      const match = results.find(r => r.name && looksLikeSamePlace(name, r.name)) ?? null;
      const id = match?.place_id ?? null;
      searchCache.set(key, id);
      resolve(id);
    });
  });
}

/** Runs `worker` over `items` with bounded concurrency, preserving input order. */
async function mapWithLimit<T, R>(items: T[], limit: number, worker: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const out = new Array<R>(items.length);
  let cursor = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) {
      const i = cursor++;
      if (i >= items.length) return;
      out[i] = await worker(items[i], i);
    }
  });
  await Promise.all(runners);
  return out;
}

/**
 * Resolves generated spot names against Places.
 *
 * - permanently closed places are dropped entirely (never reach the user)
 * - places with no listing survive as `unchecked` - deleting them would strip out the
 *   street food and small local spots that make a plan worth having
 * - the model's own description is kept only when Places has nothing better
 */
export async function resolveSpots(
  candidates: SpotCandidate[],
  destinationName: string,
): Promise<ResolvedSpot[]> {
  const cleaned = candidates
    .map(c => ({ name: c.name?.trim() ?? '', description: c.description?.trim() || undefined }))
    .filter(c => c.name.length > 0);

  if (cleaned.length === 0) return [];

  // No SDK (key missing, offline, blocked) - degrade honestly rather than
  // silently presenting unverified places as if they had been checked.
  if (!placesAvailable()) {
    return cleaned.map(c => ({ ...c, provenance: 'unchecked' as const }));
  }

  const verifiedAt = new Date().toISOString();

  const resolved = await mapWithLimit(cleaned, 3, async (candidate): Promise<ResolvedSpot | null> => {
    let placeId: string | null = null;
    try {
      placeId = await findPlaceId(candidate.name, destinationName);
    } catch {
      placeId = null;
    }
    if (!placeId) return { ...candidate, provenance: 'unchecked' };

    const details = await getPlaceDetails(placeId).catch(() => null);
    if (!details) return { ...candidate, provenance: 'unchecked' };

    // The whole point: a place that has shut down never reaches the plan.
    if (details.businessStatus === CLOSED_PERMANENTLY) return null;

    return {
      name: details.name || candidate.name,
      description: details.description || candidate.description,
      placeId: details.placeId,
      photoUrl: details.photoUrl,
      mapUrl: details.mapUrl,
      lat: details.lat,
      lng: details.lng,
      types: details.types,
      provenance: 'verified',
      verifiedAt,
    };
  });

  return resolved.filter((s): s is ResolvedSpot => s !== null);
}
